
""" Example data:
        {'name': "loop-idle1",
            'file': "media/loop-idle1.mp4",
            'type': 'loop',                     # loop, transition, content, or 
            'start': 0.0,                       # if omitted, assumes 0
            'length': 0.0,                      # if omitted, assumes len(filename)
            'disabled': True,                   # if omitted, assumes False
         },
"""

films = [
        {'name': "loop-idle1",
            'file': "media/loop-idle1.mp4",
            'type': 'loop',
         },
        {'name': "loop-under-construction",
            'file': "media/loop-under-construction.mp4",
            'type': 'loop'
            'disabled': True,
         },
        {'name': "loop-cold-night",
            'file': "media/loop-cold-night.mp4",
            'type': 'loop',
            'disabled': True,
         },
        {'name': "loop-swamp",
            'file': "media/loop-swamp.mp4",
            'type': 'loop',
            'disabled': True,
         },

        {'name': "tv-color-bars-distorted",
            'file': "media/tv-color-bars-distorted.mp4",
            'type': 'transition',
            'length': 1.0,
         },
        {'name': "tv-color-bars",
            'file': "media/tv-color-bars.mp4",
            'type': 'transition',
            'length': 1.0,
            'disabled': True,
         },
        {'name': "tv-color-calibration",
            'file': "media/tv-color-calibration.mp4",
            'type': 'transition',
            'length': 1.0,
         },
        {'name': "tv-static-transition",
            'file': "media/tv-static-transition.mp4",
            'type': 'transition',
            'length': 1.0,
         },

        {'name': "content-remote 1",
            'file': "media/content-remote1.mp4",
            'type': 'content',
            'length': 45.0,
         },
        {'name': "content-remote 2",
            'file': "media/content-remote1.mp4",
            'type': 'content',
            'start': 45.0,
            'length': 45.0,
         },
        {'name': "content-remote 3",
            'file': "media/content-remote1.mp4",
            'type': 'content',
            'start': 90.0,
            'length': 45.0,
         },
        {'name': "content-remote 4",
            'file': "media/content-remote1.mp4",
            'type': 'content',
            'start': 135.0,
            'length': 45.0,
         },
        {'name': "content-hair 1",
            'file': "media/content-hair1.mp4",
            'type': 'content',
            'length': 45.0,
         },
        {'name': "content-phone 1",
            'file': "media/content-phone1.mp4",
            'type': 'content',
            'length': 51.0,
         },
        {'name': "1960s-baltimore-family",
            'file': "media/1960s-baltimore-family.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'name': "1960s-cuba-family",
            'file': "media/1960s-cuba-family.mp4",
            'type': 'content',
            'length': 20.0,
         },
        {'name': "1960s-family-movie",
            'file': "media/1960s-family-movie.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'name': "1960s-family-vacation-keys",
            'file': "media/1960s-family-vacation-keys.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'name': "1960s-suburban-family",
            'file': "media/1960s-suburban-family.mp4",
            'type': 'content',
            'length': 5.0,
         },
        {'name': "1960s-uncle-howie-house",
            'file': "media/1960s-uncle-howie-house.mp4",
            'type': 'content',
            'length': 5.0,
         },
    ]
